// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Gx.Atom
{

    /// <remarks>
    ///  identifies the agent used to generate a feed, for debugging and other purposes.
    /// </remarks>
    /// <summary>
    ///  identifies the agent used to generate a feed, for debugging and other purposes.
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://www.w3.org/2005/Atom", TypeName = "Generator")]
    public sealed partial class Generator
    {

        private string _base;
        private string _uri;
        private string _lang;
        private string _version;
        private string _value;
        /// <summary>
        ///  The base.
        /// </summary>
        [XmlAttribute(AttributeName = "base")]
        [JsonProperty("base")]
        public string Base
        {
            get
            {
                return this._base;
            }
            set
            {
                this._base = value;
            }
        }
        /// <summary>
        ///  link to a representation that is relevant to the generating agent.
        /// </summary>
        [XmlAttribute(AttributeName = "uri")]
        [JsonProperty("uri")]
        public string Uri
        {
            get
            {
                return this._uri;
            }
            set
            {
                this._uri = value;
            }
        }
        /// <summary>
        ///  The language.
        /// </summary>
        [XmlAttribute(AttributeName = "lang", Namespace = "http://www.w3.org/XML/1998/namespace")]
        [JsonProperty("lang")]
        public string Lang
        {
            get
            {
                return this._lang;
            }
            set
            {
                this._lang = value;
            }
        }
        /// <summary>
        ///  the version of the generating agent
        /// </summary>
        [XmlAttribute(AttributeName = "version")]
        [JsonProperty("version")]
        public string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
        /// <summary>
        ///  human-readable name for the generating agent
        /// </summary>
        [XmlTextAttribute()]
        [JsonProperty("value")]
        public string Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
    }
}
