// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Linq;

using Gedcomx.Model.Rt;

using Gx.Common;
using Gx.Records;

namespace Gx.Conclusion
{

    /// <remarks>
    ///  A concluded genealogical date.
    /// </remarks>
    /// <summary>
    ///  A concluded genealogical date.
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://gedcomx.org/v1/", TypeName = "Date")]
    public partial class DateInfo : Gx.Common.ExtensibleData
    {

        private string _original;
        private string _formal;
        private System.Collections.Generic.List<Gx.Common.TextValue> _normalizedExtensions;
        private System.Collections.Generic.List<Gx.Records.Field> _fields;
        /// <summary>
        ///  The original text as supplied by the user.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "original", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("original")]
        public string Original
        {
            get
            {
                return this._original;
            }
            set
            {
                this._original = value;
            }
        }
        /// <summary>
        ///  The formal value.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "formal", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("formal")]
        public string Formal
        {
            get
            {
                return this._formal;
            }
            set
            {
                this._formal = value;
            }
        }
        /// <summary>
        ///  The list of normalized values for the date, provided for display purposes by the application. Normalized values
        ///  are not specified by GEDCOM X core, but as extension elements by GEDCOM X RS.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "normalized", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("normalized")]
        public System.Collections.Generic.List<Gx.Common.TextValue> NormalizedExtensions
        {
            get
            {
                return this._normalizedExtensions ?? (_normalizedExtensions = new System.Collections.Generic.List<Gx.Common.TextValue>());
            }
            set
            {
                this._normalizedExtensions = value;
            }
        }
        public bool ShouldSerializeNormalizedExtensions() => AnyNormalizedExtensions();
        public bool AnyNormalizedExtensions()
        {
            return _normalizedExtensions?.Any() ?? false;
        }
        /// <summary>
        ///  The references to the record fields being used as evidence.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "field", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("fields")]
        public System.Collections.Generic.List<Gx.Records.Field> Fields
        {
            get
            {
                return this._fields ?? (_fields = new System.Collections.Generic.List<Gx.Records.Field>());
            }
            set
            {
                this._fields = value;
            }
        }
        public bool ShouldSerializeFields() => AnyFields();
        public bool AnyFields()
        {
            return _fields?.Any() ?? false;
        }

        /**
         * Accept a visitor.
         *
         * @param visitor The visitor.
         */
        public void Accept(IGedcomxModelVisitor visitor)
        {
            visitor.VisitDate(this);
        }

        /**
         * Build up this date with original text as supplied by the user.
         *
         * @param original the original text.
         * @return this.
         */
        public DateInfo SetOriginal(String original)
        {
            Original = original;
            return this;
        }

        /**
         * Build up this normalized extension to the list.
         *
         * @param normalizedExtension The normalizedExtension to be added.
         */
        public void SetNormalizedExtension(TextValue normalizedExtension)
        {
            if (normalizedExtension != null)
            {
                NormalizedExtensions.Add(normalizedExtension);
            }
        }

        /**
         * Build up this date with a formal representation of the date.
         *
         * @param formal The formal date.
         * @return this.
         */
        public DateInfo SetFormal(String formal)
        {
            Formal = formal;
            return this;
        }

        /**
         * Build up this date with a field.
         *
         * @param field The field.
         * @return this.
         */
        public DateInfo SetField(Field field)
        {
            if (field != null)
            {
                Fields.Add(field);
            }
            return this;
        }
    }
}
