// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Gx.Types {

  /// <remarks>
  ///  Enumeration of known facet types.
  /// </remarks>
  /// <summary>
  ///  Enumeration of known facet types.
  /// </summary>
  public enum FacetType {

    /// <summary>
    ///  Unspecified enum value.
    /// </summary>
    [XmlEnumAttribute(Name="__NULL__")]
    NULL,

    /// <summary>
    ///   A year.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Year")]
    Year,

    /// <summary>
    ///   A (geographic) state.
    /// </summary>
    [XmlEnum("http://gedcomx.org/State")]
    State,

    /// <summary>
    ///   A province.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Province")]
    Province,

    /// <summary>
    ///   A country.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Country")]
    Country,

    /// <summary>
    ///   A city.
    /// </summary>
    [XmlEnum("http://gedcomx.org/City")]
    City,

    /// <summary>
    ///   A parish
    /// </summary>
    [XmlEnum("http://gedcomx.org/Parish")]
    Parish,

    /// <summary>
    ///   A township.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Township")]
    Township,

    /// <summary>
    ///   A page.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Page")]
    Page,

    /// <summary>
    ///   A volume.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Volume")]
    Volume,

    /// <summary>
    ///   A date.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Date")]
    Date,

    /// <summary>
    ///   A place.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Place")]
    Place,

    /// <summary>
    ///   A name.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Name")]
    Name,

    /// <summary>
    ///   A gender.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Gender")]
    Gender,

    /// <summary>
    ///   Custom
    /// </summary>
    [XmlEnum("http://gedcomx.org/OTHER")]
    OTHER
  }
}
