// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel;

namespace Gx.Records
{

    /// <remarks>
    ///  &lt;p&gt;A facet value is the value that is used by a facet to group related resources.&lt;/p&gt;
    /// </remarks>
    /// <summary>
    ///  &lt;p&gt;A facet value is the value that is used by a facet to group related resources.&lt;/p&gt;
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://gedcomx.org/v1/", TypeName = "FacetValue")]
    public partial class FacetValue : Gx.Links.HypermediaEnabledData
    {

        private string _title;
        private string _value;
        private int? _count;
        private bool _countSpecified;
        /// <summary>
        ///  A title for the facet value.
        /// </summary>
        [XmlElement(ElementName = "title", Namespace = "http://gedcomx.org/v1/")]
        [JsonProperty("title")]
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        /// <summary>
        ///  The value.
        /// </summary>
        [XmlElement(ElementName = "value", Namespace = "http://gedcomx.org/v1/")]
        [JsonProperty("value")]
        public string Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        /// <summary>
        ///  The number of resources applicable to this value.
        /// </summary>
        [XmlElement(ElementName = "count", Namespace = "http://gedcomx.org/v1/")]
        [JsonProperty("count")]
        public int Count
        {
            get
            {
                return this._count.GetValueOrDefault();
            }
            set
            {
                this._count = value;
                this._countSpecified = true;
            }
        }

        /// <summary>
        ///  Property for the XML serializer indicating whether the "Count" property should be included in the output.
        /// </summary>
        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [JsonIgnore]
        public bool CountSpecified
        {
            get
            {
                return this._countSpecified;
            }
            set
            {
                this._countSpecified = value;
            }
        }

    }
}
