// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Records {

  /// <remarks>
  ///  A description of a field in a record.
  /// </remarks>
  /// <summary>
  ///  A description of a field in a record.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="FieldDescriptor")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="FieldDescriptor")]
  public partial class FieldDescriptor : Gx.Links.HypermediaEnabledData {

    private string _fieldId;
    private string _originalLabel;
    private System.Collections.Generic.List<Gx.Common.TextValue> _description;
    private System.Collections.Generic.List<Gx.Records.FieldValueDescriptor> _values;
    /// <summary>
    ///  A system-assigned label for the field.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="fieldId")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="fieldId")]
    public string FieldId {
      get {
        return this._fieldId;
      }
      set {
        this._fieldId = value;
      }
    }
    /// <summary>
    ///  The original label for the field, as stated on the original record.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="originalLabel",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="originalLabel")]
    public string OriginalLabel {
      get {
        return this._originalLabel;
      }
      set {
        this._originalLabel = value;
      }
    }
    /// <summary>
    ///  The description of the field.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="description",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="description")]
    public System.Collections.Generic.List<Gx.Common.TextValue> Description {
      get {
        return this._description;
      }
      set {
        this._description = value;
      }
    }
    /// <summary>
    ///  Descriptors of the values that are applicable to the field.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="value",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="value")]
    public System.Collections.Generic.List<Gx.Records.FieldValueDescriptor> Values {
      get {
        return this._values;
      }
      set {
        this._values = value;
      }
    }
  }
}  
