// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx {

  /// <remarks>
  ///  &lt;p&gt;The GEDCOM X data formats define the serialization formats of the GEDCOM X conceptual model. The canonical documentation
  ///  is provided by the formal specification documents:&lt;/p&gt;
  ///  
  ///  &lt;ul&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md&quot;&gt;The GEDCOM X Conceptual Model, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md&quot;&gt;The GEDCOM X JSON Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/xml-format-specification.md&quot;&gt;The GEDCOM X XML Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;/ul&gt;
  ///  
  ///  &lt;p&gt;This documentation is provided as a non-normative reference guide.&lt;/p&gt;
  /// </remarks>
  /// <summary>
  ///  &lt;p&gt;The GEDCOM X data formats define the serialization formats of the GEDCOM X conceptual model. The canonical documentation
  ///  is provided by the formal specification documents:&lt;/p&gt;
  ///  
  ///  &lt;ul&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md&quot;&gt;The GEDCOM X Conceptual Model, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md&quot;&gt;The GEDCOM X JSON Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/xml-format-specification.md&quot;&gt;The GEDCOM X XML Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;/ul&gt;
  ///  
  ///  &lt;p&gt;This documentation is provided as a non-normative reference guide.&lt;/p&gt;
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gedcomx")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gedcomx")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://gedcomx.org/v1/",ElementName="gedcomx")]
  public partial class Gedcomx : Gx.Links.HypermediaEnabledData {

    private string _lang;
    private string _descriptionRef;
    private string _profile;
    private Gx.Common.Attribution _attribution;
    private System.Collections.Generic.List<Gx.Conclusion.Person> _persons;
    private System.Collections.Generic.List<Gx.Conclusion.Relationship> _relationships;
    private System.Collections.Generic.List<Gx.Source.SourceDescription> _sourceDescriptions;
    private System.Collections.Generic.List<Gx.Agent.Agent> _agents;
    private System.Collections.Generic.List<Gx.Conclusion.Event> _events;
    private System.Collections.Generic.List<Gx.Conclusion.PlaceDescription> _places;
    private System.Collections.Generic.List<Gx.Conclusion.Document> _documents;
    private System.Collections.Generic.List<Gx.Records.Collection> _collections;
    private System.Collections.Generic.List<Gx.Records.Field> _fields;
    private System.Collections.Generic.List<Gx.Records.RecordDescriptor> _recordDescriptors;
    /// <summary>
    ///  The language of the genealogical data.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="lang",Namespace="http://www.w3.org/XML/1998/namespace")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="lang",Namespace="http://www.w3.org/XML/1998/namespace")]
    public string Lang {
      get {
        return this._lang;
      }
      set {
        this._lang = value;
      }
    }
    /// <summary>
    ///  A reference to a description of this data set.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="description")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="description")]
    public string DescriptionRef {
      get {
        return this._descriptionRef;
      }
      set {
        this._descriptionRef = value;
      }
    }
    /// <summary>
    ///  A reference to the profile that describes this data set.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="profile")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="profile")]
    public string Profile {
      get {
        return this._profile;
      }
      set {
        this._profile = value;
      }
    }
    /// <summary>
    ///  The attribution of this genealogical data.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="attribution",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="attribution")]
    public Gx.Common.Attribution Attribution {
      get {
        return this._attribution;
      }
      set {
        this._attribution = value;
      }
    }
    /// <summary>
    ///  The persons included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="person",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="person")]
    public System.Collections.Generic.List<Gx.Conclusion.Person> Persons {
      get {
        return this._persons;
      }
      set {
        this._persons = value;
      }
    }
    /// <summary>
    ///  The relationships included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="relationship",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="relationship")]
    public System.Collections.Generic.List<Gx.Conclusion.Relationship> Relationships {
      get {
        return this._relationships;
      }
      set {
        this._relationships = value;
      }
    }
    /// <summary>
    ///  The descriptions of sources included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="sourceDescription",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="sourceDescription")]
    public System.Collections.Generic.List<Gx.Source.SourceDescription> SourceDescriptions {
      get {
        return this._sourceDescriptions;
      }
      set {
        this._sourceDescriptions = value;
      }
    }
    /// <summary>
    ///  The agents included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="agent",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="agent")]
    public System.Collections.Generic.List<Gx.Agent.Agent> Agents {
      get {
        return this._agents;
      }
      set {
        this._agents = value;
      }
    }
    /// <summary>
    ///  The events included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="event",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="event")]
    public System.Collections.Generic.List<Gx.Conclusion.Event> Events {
      get {
        return this._events;
      }
      set {
        this._events = value;
      }
    }
    /// <summary>
    ///  The places included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="place",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="place")]
    public System.Collections.Generic.List<Gx.Conclusion.PlaceDescription> Places {
      get {
        return this._places;
      }
      set {
        this._places = value;
      }
    }
    /// <summary>
    ///  The documents included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="document",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="document")]
    public System.Collections.Generic.List<Gx.Conclusion.Document> Documents {
      get {
        return this._documents;
      }
      set {
        this._documents = value;
      }
    }
    /// <summary>
    ///  The collections included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="collection",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="collection")]
    public System.Collections.Generic.List<Gx.Records.Collection> Collections {
      get {
        return this._collections;
      }
      set {
        this._collections = value;
      }
    }
    /// <summary>
    ///  The extracted fields included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="field",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="field")]
    public System.Collections.Generic.List<Gx.Records.Field> Fields {
      get {
        return this._fields;
      }
      set {
        this._fields = value;
      }
    }
    /// <summary>
    ///  The record descriptors included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="recordDescriptor",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="recordDescriptor")]
    public System.Collections.Generic.List<Gx.Records.RecordDescriptor> RecordDescriptors {
      get {
        return this._recordDescriptors;
      }
      set {
        this._recordDescriptors = value;
      }
    }
  }
}  
