// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Conclusion {

  /// <remarks>
  ///  A gender conclusion.
  /// </remarks>
  /// <summary>
  ///  A gender conclusion.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gender")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gender")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://gedcomx.org/v1/",ElementName="gender")]
  public partial class Gender : Gx.Conclusion.Conclusion {

    private string _type;
    private System.Collections.Generic.List<Gx.Common.EvidenceReference> _fieldValueReferences;
    /// <summary>
    ///  The type of the gender.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="type")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="type")]
    public string Type {
      get {
        return this._type;
      }
      set {
        this._type = value;
      }
    }

    /// <summary>
    ///  Convenience property for treating Type as an enum. See Gx.Types.GenderTypeQNameUtil for details on getter/setter functionality.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    public Gx.Types.GenderType KnownType {
      get {
        return Gx.Types.GenderTypeQNameUtil.ConvertFromKnownQName(this._type);
      }
      set {
        this._type = Gx.Types.GenderTypeQNameUtil.ConvertToKnownQName(value);
      }
    }
    /// <summary>
    ///  The references to the record field values being used as evidence.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="fieldValue",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="fieldValue")]
    public System.Collections.Generic.List<Gx.Common.EvidenceReference> FieldValueReferences {
      get {
        return this._fieldValueReferences;
      }
      set {
        this._fieldValueReferences = value;
      }
    }
  }
}  
