// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Links {

  /// <remarks>
  ///  A hypermedia link, used to drive the state of a hypermedia-enabled genealogical data application.
  /// </remarks>
  /// <summary>
  ///  A hypermedia link, used to drive the state of a hypermedia-enabled genealogical data application.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Link")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Link")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://gedcomx.org/v1/",ElementName="link")]
  public partial class Link {

    private string _hreflang;
    private string _template;
    private string _title;
    private string _allow;
    private string _accept;
    private string _rel;
    private string _type;
    private string _href;
    /// <summary>
    ///  The language of the resource being linked to.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="hreflang")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="hreflang")]
    public string Hreflang {
      get {
        return this._hreflang;
      }
      set {
        this._hreflang = value;
      }
    }
    /// <summary>
    ///  A URI template per &lt;a href=&quot;http://tools.ietf.org/html/rfc6570&quot;&gt;RFC 6570&lt;/a&gt;, used to link to a range of
    ///  URIs, such as for the purpose of linking to a query.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="template")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="template")]
    public string Template {
      get {
        return this._template;
      }
      set {
        this._template = value;
      }
    }
    /// <summary>
    ///  Human-readable information about the link.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="title")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="title")]
    public string Title {
      get {
        return this._title;
      }
      set {
        this._title = value;
      }
    }
    /// <summary>
    ///  Metadata about the available media type(s) of the resource being linked to.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="allow")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="allow")]
    public string Allow {
      get {
        return this._allow;
      }
      set {
        this._allow = value;
      }
    }
    /// <summary>
    ///  Metadata about the available media type(s) of the resource being linked to.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="accept")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="accept")]
    public string Accept {
      get {
        return this._accept;
      }
      set {
        this._accept = value;
      }
    }
    /// <summary>
    ///  The link relationship.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="rel")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="rel")]
    public string Rel {
      get {
        return this._rel;
      }
      set {
        this._rel = value;
      }
    }
    /// <summary>
    ///  Metadata about the available media type(s) of the resource being linked to.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="type")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="type")]
    public string Type {
      get {
        return this._type;
      }
      set {
        this._type = value;
      }
    }
    /// <summary>
    ///  The target IRI of the link.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="href")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="href")]
    public string Href {
      get {
        return this._href;
      }
      set {
        this._href = value;
      }
    }
  }
}  
