// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Gx.Types {

  /// <remarks>
  ///  Enumeration of standard name types.
  /// </remarks>
  /// <summary>
  ///  Enumeration of standard name types.
  /// </summary>
  public enum NameType {

    /// <summary>
    ///  Unspecified enum value.
    /// </summary>
    [XmlEnumAttribute(Name="__NULL__")]
    NULL,

    /// <summary>
    ///   Name given at birth.
    /// </summary>
    [XmlEnum("http://gedcomx.org/BirthName")]
    BirthName,

    /// <summary>
    ///   Name used at the time of death.
    /// </summary>
    [XmlEnum("http://gedcomx.org/DeathName")]
    DeathName,

    /// <summary>
    ///   Name accepted at marriage.
    /// </summary>
    [XmlEnum("http://gedcomx.org/MarriedName")]
    MarriedName,

    /// <summary>
    ///   &quot;Also known as&quot; name.
    /// </summary>
    [XmlEnum("http://gedcomx.org/AlsoKnownAs")]
    AlsoKnownAs,

    /// <summary>
    ///   Nickname.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Nickname")]
    Nickname,

    /// <summary>
    ///   Name given at adoption.
    /// </summary>
    [XmlEnum("http://gedcomx.org/AdoptiveName")]
    AdoptiveName,

    /// <summary>
    ///   A formal name, usually given to distinguish it from a name more commonly used.
    /// </summary>
    [XmlEnum("http://gedcomx.org/FormalName")]
    FormalName,

    /// <summary>
    ///   A name given at a religious rite or ceremony.
    /// </summary>
    [XmlEnum("http://gedcomx.org/ReligiousName")]
    ReligiousName,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [XmlEnum("http://gedcomx.org/OTHER")]
    OTHER
  }
}
