// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Conclusion {

  /// <remarks>
  ///  A reference to genealogical place.
  /// </remarks>
  /// <summary>
  ///  A reference to genealogical place.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="PlaceReference")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="PlaceReference")]
  public partial class PlaceReference : Gx.Common.ExtensibleData {

    private string _descriptionRef;
    private string _original;
    private System.Collections.Generic.List<Gx.Records.Field> _fields;
    /// <summary>
    ///  A reference to a description of the place being referenced.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="description")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="description")]
    public string DescriptionRef {
      get {
        return this._descriptionRef;
      }
      set {
        this._descriptionRef = value;
      }
    }
    /// <summary>
    ///  The original value as supplied by the user.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="original",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="original")]
    public string Original {
      get {
        return this._original;
      }
      set {
        this._original = value;
      }
    }
    /// <summary>
    ///  The references to the record fields being used as evidence.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="field",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="field")]
    public System.Collections.Generic.List<Gx.Records.Field> Fields {
      get {
        return this._fields;
      }
      set {
        this._fields = value;
      }
    }
  }
}  
