// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Gx.Records
{

    /// <remarks>
    ///  The GEDCOM X bulk record data formats are used to exchange bulk genealogical data sets, grouped into records.
    /// </remarks>
    /// <summary>
    ///  The GEDCOM X bulk record data formats are used to exchange bulk genealogical data sets, grouped into records.
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://gedcomx.org/v1/", TypeName = "RecordSet")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://gedcomx.org/v1/", ElementName = "records")]
    public partial class RecordSet : Gx.Links.HypermediaEnabledData
    {

        private string _lang;
        private Gx.Gedcomx _metadata;
        private System.Collections.Generic.List<Gx.Gedcomx> _records;
        /// <summary>
        ///  The language of the genealogical data.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "lang", Namespace = "http://www.w3.org/XML/1998/namespace")]
        [Newtonsoft.Json.JsonProperty("lang")]
        public string Lang
        {
            get
            {
                return this._lang;
            }
            set
            {
                this._lang = value;
            }
        }
        /// <summary>
        ///  Metadata about this record set; shared among all records in the set.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "metadata", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("metadata")]
        public Gx.Gedcomx Metadata
        {
            get
            {
                return this._metadata;
            }
            set
            {
                this._metadata = value;
            }
        }
        /// <summary>
        ///  The records included in this genealogical data set.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "record", Namespace = "http://gedcomx.org/v1/")]
        [Newtonsoft.Json.JsonProperty("records")]
        public System.Collections.Generic.List<Gx.Gedcomx> Records
        {
            get
            {
                return this._records;
            }
            set
            {
                this._records = value;
            }
        }

        /**
         * Build out this record set with a lang.
         * @param lang The lang.
         * @return this.
         */
        public RecordSet SetLang(String lang)
        {
            Lang = lang;
            return this;
        }

        /**
         * Build out this record set with metadata.
         *
         * @param metadata The metadata.
         * @return this.
         */
        public RecordSet SetMetadata(Gedcomx metadata)
        {
            Metadata = metadata;
            return this;
        }

        /**
         * Build out this record set with a record.
         * @param record The record.
         * @return this.
         */
        public RecordSet SetRecord(Gedcomx record)
        {
            if (this._records == null)
            {
                this._records = new List<Gedcomx>();
            }
            this._records.Add(record);
            return this;
        }
    }
}
