// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Fs.Artifacts {

  /// <remarks>
  ///  FamilySearch-specific metadata about an artifact.
  /// </remarks>
  /// <summary>
  ///  FamilySearch-specific metadata about an artifact.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://familysearch.org/v1/",TypeName="ArtifactMetadata")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://familysearch.org/v1/",TypeName="ArtifactMetadata")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://familysearch.org/v1/",ElementName="artifactMetadata")]
  public partial class ArtifactMetadata {

    private string _artifactType;
    private string _filename;
    /// <summary>
    ///  The type of the gender.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="artifactType")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="artifactType")]
    public string ArtifactType {
      get {
        return this._artifactType;
      }
      set {
        this._artifactType = value;
      }
    }

    /// <summary>
    ///  Convenience property for treating ArtifactType as an enum. See Gx.Fs.Artifacts.ArtifactTypeQNameUtil for details on getter/setter functionality.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    public Gx.Fs.Artifacts.ArtifactType KnownArtifactType {
      get {
        return Gx.Fs.Artifacts.ArtifactTypeQNameUtil.ConvertFromKnownQName(this._artifactType);
      }
      set {
        this._artifactType = Gx.Fs.Artifacts.ArtifactTypeQNameUtil.ConvertToKnownQName(value);
      }
    }
    /// <summary>
    ///  The original filename of the memories item.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="filename",Namespace="http://familysearch.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="filename")]
    public string Filename {
      get {
        return this._filename;
      }
      set {
        this._filename = value;
      }
    }
  }
}  
