// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Gx.Fs.Tree {

  /// <remarks>
  ///  Enumeration of the possible change object modifiers.
  /// </remarks>
  /// <summary>
  ///  Enumeration of the possible change object modifiers.
  /// </summary>
  public enum ChangeObjectModifier {

    /// <summary>
    ///  Unspecified enum value.
    /// </summary>
    [XmlEnumAttribute(Name="__NULL__")]
    NULL,

    /// <summary>
    ///   The person.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Person")]
    Person,

    /// <summary>
    ///   The couple.
    /// </summary>
    [XmlEnum("http://gedcomx.org/Couple")]
    Couple,

    /// <summary>
    ///   The child-and-parents relationship.
    /// </summary>
    [XmlEnum("http://familysearch.org/v1/ChildAndParentsRelationship")]
    ChildAndParentsRelationship
  }
}
