using Gedcomx.Model.Util;
using Gx.Common;
using Gx.Fs.Rt;
// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel;

namespace Gx.Fs.Discussions
{

    /// <remarks>
    ///  
    /// </remarks>
    /// <summary>
    ///  
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://familysearch.org/v1/", TypeName = "Comment")]
    public partial class Comment : Gx.Links.HypermediaEnabledData
    {

        private string _text;
        private DateTime? _created;
        private bool _createdSpecified;
        private Gx.Common.ResourceReference _contributor;
        /// <summary>
        ///  The text or &quot;message body&quot; of the comment
        /// </summary>
        [XmlElement(ElementName = "text", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("text")]
        public string Text
        {
            get
            {
                return this._text;
            }
            set
            {
                this._text = value;
            }
        }
        /// <summary>
        ///  date of creation
        /// </summary>
        [XmlElement(ElementName = "created", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("created")]
        [JsonConverter(typeof(JsonUnixTimestampConverter))]
        public DateTime Created
        {
            get
            {
                return this._created.GetValueOrDefault();
            }
            set
            {
                this._created = value;
                this._createdSpecified = true;
            }
        }

        /// <summary>
        ///  Property for the XML serializer indicating whether the "Created" property should be included in the output.
        /// </summary>
        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [JsonIgnore]
        public bool CreatedSpecified
        {
            get
            {
                return this._createdSpecified;
            }
            set
            {
                this._createdSpecified = value;
            }
        }

        /// <summary>
        ///  contributor of comment
        /// </summary>
        [XmlElement(ElementName = "contributor", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("contributor")]
        public Gx.Common.ResourceReference Contributor
        {
            get
            {
                return this._contributor;
            }
            set
            {
                this._contributor = value;
            }
        }

        /**
         * Accept a visitor.
         *
         * @param visitor The visitor to accept.
         */
        public void Accept(IFamilySearchPlatformModelVisitor visitor)
        {
            visitor.VisitComment(this);
        }

        internal void EmbedInt(ExtensibleData value)
        {
            this.Embed(value);
        }

        /**
         * Update this comment by applying text.
         *
         * @param text The text to apply.
         * @return The comment.
         */
        public Comment SetText(String text)
        {
            Text = text;
            return this;
        }

        /**
         * Build this comment by applying a contributor.
         *
         * @param contributor The contributor.
         * @return this.
         */
        public Comment SetContributor(ResourceReference contributor)
        {
            Contributor = contributor;
            return this;
        }

        /**
         * Build this comment by applying a created date.
         *
         * @param created The created date.
         * @return The comment.
         */
        public Comment SetCreated(DateTime created)
        {
            Created = created;
            return this;
        }
    }
}
