using Gedcomx.Model.Util;
// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel;

namespace Gx.Fs
{

    /// <remarks>
    ///  A description of a FamilySearch feature.
    /// </remarks>
    /// <summary>
    ///  A description of a FamilySearch feature.
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://familysearch.org/v1/", TypeName = "FeatureSet")]
    public partial class Feature
    {

        private string _name;
        private string _description;
        private bool? _enabled;
        private bool _enabledSpecified;
        private DateTime? _activationDate;
        private bool _activationDateSpecified;
        /// <summary>
        ///  The name of the feature.
        /// </summary>
        [XmlElement(ElementName = "name", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        /// <summary>
        ///  A description of the feature.
        /// </summary>
        [XmlElement(ElementName = "description", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("description")]
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        /// <summary>
        ///  Whether the feature is enabled for the current request.
        /// </summary>
        [XmlElement(ElementName = "enabled", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("enabled")]
        public bool Enabled
        {
            get
            {
                return this._enabled.GetValueOrDefault();
            }
            set
            {
                this._enabled = value;
                this._enabledSpecified = true;
            }
        }

        /// <summary>
        ///  Property for the XML serializer indicating whether the "Enabled" property should be included in the output.
        /// </summary>
        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [JsonIgnore]
        public bool EnabledSpecified
        {
            get
            {
                return this._enabledSpecified;
            }
            set
            {
                this._enabledSpecified = value;
            }
        }

        /// <summary>
        ///  The date that this feature is scheduled to activate permanently.
        /// </summary>
        [XmlElement(ElementName = "activationDate", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("activationDate")]
        [JsonConverter(typeof(JsonUnixTimestampConverter))]
        public DateTime ActivationDate
        {
            get
            {
                return this._activationDate.GetValueOrDefault();
            }
            set
            {
                this._activationDate = value;
                this._activationDateSpecified = true;
            }
        }

        /// <summary>
        ///  Property for the XML serializer indicating whether the "ActivationDate" property should be included in the output.
        /// </summary>
        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [JsonIgnore]
        public bool ActivationDateSpecified
        {
            get
            {
                return this._activationDateSpecified;
            }
            set
            {
                this._activationDateSpecified = value;
            }
        }

    }
}
