// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Fs
{

    /// <remarks>
    ///  
    /// </remarks>
    /// <summary>
    ///  
    /// </summary>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://familysearch.org/v1/", TypeName = "HealthConfig")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://familysearch.org/v1/", ElementName = "healthConfig")]
    public partial class HealthConfig
    {

        private string _buildDate;
        private string _buildVersion;
        private string _databaseVersion;
        private string _platformVersion;
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "buildDate", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("buildDate")]
        public string BuildDate
        {
            get
            {
                return this._buildDate;
            }
            set
            {
                this._buildDate = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "buildVersion", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("buildVersion")]
        public string BuildVersion
        {
            get
            {
                return this._buildVersion;
            }
            set
            {
                this._buildVersion = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "databaseVersion", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("databaseVersion")]
        public string DatabaseVersion
        {
            get
            {
                return this._databaseVersion;
            }
            set
            {
                this._databaseVersion = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "platformVersion", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("platformVersion")]
        public string PlatformVersion
        {
            get
            {
                return this._platformVersion;
            }
            set
            {
                this._platformVersion = value;
            }
        }
    }
}
