// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System.Xml.Serialization;

namespace Gx.Fs.Tree
{

    /// <remarks>
    ///  The way a match was resolved.
    /// </remarks>
    /// <summary>
    ///  The way a match was resolved.
    /// </summary>
    public enum MatchStatus
    {

        /// <summary>
        ///  Unspecified enum value.
        /// </summary>
        [XmlEnum(Name = "__NULL__")]
        NULL,

        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [XmlEnum("http://familysearch.org/v1/Pending")]
        Pending,

        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [XmlEnum("http://familysearch.org/v1/Accepted")]
        Accepted,

        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [XmlEnum("http://familysearch.org/v1/Rejected")]
        Rejected
    }
}
