using Gx.Fs.Rt;
// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using System.Collections.Generic;

namespace Gx.Fs.Tree
{

    /// <remarks>
    ///  
    /// </remarks>
    /// <summary>
    ///  
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://familysearch.org/v1/", TypeName = "MergeAnalysis")]
    [XmlRoot(Namespace = "http://familysearch.org/v1/", ElementName = "mergeAnalysis")]
    public partial class MergeAnalysis
    {

        private List<Gx.Common.ResourceReference> _survivorResources;
        private List<Gx.Common.ResourceReference> _duplicateResources;
        private List<Gx.Fs.Tree.MergeConflict> _conflictingResources;
        private Gx.Common.ResourceReference _survivor;
        private Gx.Common.ResourceReference _duplicate;
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "survivorResource", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("survivorResources")]
        public List<Gx.Common.ResourceReference> SurvivorResources
        {
            get
            {
                return this._survivorResources;
            }
            set
            {
                this._survivorResources = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "duplicateResource", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("duplicateResources")]
        public List<Gx.Common.ResourceReference> DuplicateResources
        {
            get
            {
                return this._duplicateResources;
            }
            set
            {
                this._duplicateResources = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "conflictingResource", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("conflictingResources")]
        public List<Gx.Fs.Tree.MergeConflict> ConflictingResources
        {
            get
            {
                return this._conflictingResources;
            }
            set
            {
                this._conflictingResources = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "survivor", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("survivor")]
        public Gx.Common.ResourceReference Survivor
        {
            get
            {
                return this._survivor;
            }
            set
            {
                this._survivor = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "duplicate", Namespace = "http://familysearch.org/v1/")]
        [Newtonsoft.Json.JsonProperty("duplicate")]
        public Gx.Common.ResourceReference Duplicate
        {
            get
            {
                return this._duplicate;
            }
            set
            {
                this._duplicate = value;
            }
        }

        /**
         * Accept a visitor.
         *
         * @param visitor The visitor to accept.
         */
        public void Accept(IFamilySearchPlatformModelVisitor visitor)
        {
            visitor.VisitMerge(this);
        }
    }
}
