// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;
using System.Xml.Serialization;
using Newtonsoft.Json;


namespace Gx.Fs.Tree
{

    /// <remarks>
    ///  
    /// </remarks>
    /// <summary>
    ///  
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://familysearch.org/v1/", TypeName = "MergeConflict")]
    [XmlRoot(Namespace = "http://familysearch.org/v1/", ElementName = "mergeConflict")]
    public partial class MergeConflict
    {

        private Gx.Common.ResourceReference _survivorResource;
        private Gx.Common.ResourceReference _duplicateResource;
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [XmlElement(ElementName = "survivorResource", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("survivorResource")]
        public Gx.Common.ResourceReference SurvivorResource
        {
            get
            {
                return this._survivorResource;
            }
            set
            {
                this._survivorResource = value;
            }
        }
        /// <summary>
        ///  (no documentation provided)
        /// </summary>
        [XmlElement(ElementName = "duplicateResource", Namespace = "http://familysearch.org/v1/")]
        [JsonProperty("duplicateResource")]
        public Gx.Common.ResourceReference DuplicateResource
        {
            get
            {
                return this._duplicateResource;
            }
            set
            {
                this._duplicateResource = value;
            }
        }
    }
}
